### ISSUE TITLE
Mesabrook Server

### ISSUE THREAD

**Issue by Shadowevil015** [RavenholmZombie/Immersibrook#5]
Hey, I stumbled across this mod while looking at latest minecraft mods on github, and I was wondering if the Mesabrook server is public? I can't find much info about it on the website, so I thought I'd ask here.

Thanks in advance!
- Shadow

**Comment by RavenholmZombie** [comment]
Hi!

Mesabrook is currently not open to the public as we are busy building it up. We are hoping to have it ready for the public at some point in either late 2021 or early 2022.

Please continue to check our website because that's where we will announce when the server is ready for the public.

~RavenholmZombie, Mesabrook Co-Developer.
